/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import com.amazonaws.services.lambda.runtime.Context;

public class App {
    public static void main(String[] args) {
    }

    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Lambda handler method
     * @param context the Lambda request context
     * @return a string containing a message
     */
    public String handleRequest(Context context) {
        return getGreeting();
    }
}
